# .github/workflows/primary.yml
name: Manually Trigger Secondary Workflow

on:
  workflow_dispatch:

jobs:
  trigger-secondary-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger secondary workflow
        uses: ./github/workflows/secondary.yml
