name: Manually Trigger Secondary Workflow
'on':
  workflow_dispatch: null
jobs:
  trigger-secondary-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger secondary workflow
        uses: ./.github/workflows/secondary.yml
