# .github/workflows/secondary.yml
name: Secondary Workflow

on:
  workflow_call:
    inputs:
      sample_input:
        required: true
        type: string

jobs:
  run-secondary-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Print sample input
        run: echo "Sample Input${inputs.sample_input}"
        
      - name: Run a sample task
        run: echo "This is a task in the secondary workflow"
